import 'package:flutter/material.dart';
import 'package:sizer/sizer.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:trudeals_realty_crm/src/core/theme/trudeals_colors.dart';
import 'package:trudeals_realty_crm/src/core/di/injection.dart';
import 'package:trudeals_realty_crm/src/features/contacts/domain/entities/contact.dart';
import 'package:trudeals_realty_crm/src/features/contacts/domain/usecases/create_contact_usecase.dart';

class IntakeFormsPage extends StatefulWidget {
  const IntakeFormsPage({super.key});

  @override
  State<IntakeFormsPage> createState() => _IntakeFormsPageState();
}

class _IntakeFormsPageState extends State<IntakeFormsPage> {
  String _formType = 'seller';
  final _nameController = TextEditingController();
  final _phoneController = TextEditingController();
  final _emailController = TextEditingController();
  final _addressController = TextEditingController();
  final _valueController = TextEditingController();
  final _notesController = TextEditingController();

  Future<void> _submit() async {
    if (_nameController.text.isEmpty || _phoneController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Name and phone are required')));
      return;
    }

    final contact = Contact(
      id: '', // Will be generated by repo
      name: _nameController.text,
      phone: _phoneController.text,
      email: _emailController.text,
      propertyAddress: _addressController.text,
      source: 'Manual Intake',
      plan: 'undecided',
      stage: 'new',
      dealValue: double.tryParse(_valueController.text) ?? 0,
      priority: Priority.high,
      createdAt: DateTime.now(),
      leadType: _formType == 'seller' ? LeadType.seller : (_formType == 'buyer' ? LeadType.buyer : LeadType.cma),
    );

    final result = await getIt<CreateContactUseCase>().call(contact);
    result.fold(
      ifLeft: (e) => ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(e.message))),
      ifRight: (c) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Lead created successfully!')));
        _clear();
      },
    );
  }

  void _clear() {
    _nameController.clear();
    _phoneController.clear();
    _emailController.clear();
    _addressController.clear();
    _valueController.clear();
    _notesController.clear();
  }

  @override
  Widget build(BuildContext context) {
    return ListView(
      padding: EdgeInsets.symmetric(horizontal: 34.px, vertical: 20.px),
      children: [
        Container(
          padding: EdgeInsets.all(13.px),
          decoration: BoxDecoration(color: TruDealsColors.sageMist, borderRadius: BorderRadius.circular(8.px)),
          child: Text(
            "These are the CRM's intake forms — the same fields your website forms and call-center forms will post into. Submissions land in New Lead, alert Sales seats, and fire automations.",
            style: TextStyle(fontSize: 12.5.px, color: TruDealsColors.inkSoft),
          ),
        ),
        SizedBox(height: 16.px),
        Row(
          children: [
            _TypeButton(label: 'Seller Lead', isActive: _formType == 'seller', onTap: () => setState(() => _formType = 'seller')),
            SizedBox(width: 10.px),
            _TypeButton(label: 'Buyer Lead', isActive: _formType == 'buyer', onTap: () => setState(() => _formType = 'buyer')),
            SizedBox(width: 10.px),
            _TypeButton(label: 'CMA Request', isActive: _formType == 'cma', onTap: () => setState(() => _formType = 'cma')),
          ],
        ),
        SizedBox(height: 18.px),
        _FormCard(
          type: _formType,
          nameController: _nameController,
          phoneController: _phoneController,
          emailController: _emailController,
          addressController: _addressController,
          valueController: _valueController,
          notesController: _notesController,
          onSubmit: _submit,
        ),
      ],
    );
  }
}

class _TypeButton extends StatelessWidget {
  final String label;
  final bool isActive;
  final VoidCallback onTap;
  const _TypeButton({required this.label, required this.isActive, required this.onTap});

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      onPressed: onTap,
      style: ElevatedButton.styleFrom(
        backgroundColor: isActive ? TruDealsColors.sageDeep : Colors.white,
        foregroundColor: isActive ? Colors.white : TruDealsColors.ink,
        elevation: 0,
        side: const BorderSide(color: TruDealsColors.line),
      ),
      child: Text(label),
    );
  }
}

class _FormCard extends StatelessWidget {
  final String type;
  final TextEditingController nameController;
  final TextEditingController phoneController;
  final TextEditingController emailController;
  final TextEditingController addressController;
  final TextEditingController valueController;
  final TextEditingController notesController;
  final VoidCallback onSubmit;

  const _FormCard({
    required this.type,
    required this.nameController,
    required this.phoneController,
    required this.emailController,
    required this.addressController,
    required this.valueController,
    required this.notesController,
    required this.onSubmit,
  });

  @override
  Widget build(BuildContext context) {
    final title = {
      'seller': 'Seller Lead',
      'buyer': 'Buyer Lead',
      'cma': 'Market Comparison (CMA) Request',
    }[type]!;

    return Container(
      constraints: BoxConstraints(maxWidth: 520.px),
      padding: EdgeInsets.all(22.px),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(10.px),
        border: Border.all(color: TruDealsColors.line),
        boxShadow: [
          BoxShadow(color: Colors.black.withAlpha(13), offset: const Offset(0, 1), blurRadius: 2),
          BoxShadow(color: Colors.black.withAlpha(15), offset: const Offset(0, 4), blurRadius: 14),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: GoogleFonts.dmSerifDisplay(fontSize: 20.px)),
          Text('Call-center / manual intake · fields marked * are required', style: TextStyle(fontSize: 13.px, color: TruDealsColors.inkSoft)),
          SizedBox(height: 16.px),
          _FormField(label: 'Full name*', controller: nameController),
          _FormField(label: 'Phone*', controller: phoneController),
          _FormField(label: 'Email', controller: emailController),
          _FormField(label: type == 'buyer' ? 'Areas of interest' : 'Property address*', controller: addressController),
          _FormField(label: type == 'buyer' ? 'Budget' : 'Estimated value', controller: valueController, isNumber: true),
          _FormField(label: 'Notes from the call', controller: notesController),
          SizedBox(height: 16.px),
          ElevatedButton(
            onPressed: onSubmit,
            style: ElevatedButton.styleFrom(minimumSize: const Size(double.infinity, 50)),
            child: const Text('Submit lead'),
          ),
        ],
      ),
    );
  }
}

class _FormField extends StatelessWidget {
  final String label;
  final TextEditingController controller;
  final bool isNumber;
  const _FormField({required this.label, required this.controller, this.isNumber = false});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.only(bottom: 13.px),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(label, style: TextStyle(fontSize: 12.5.px, fontWeight: FontWeight.w600, color: TruDealsColors.charcoalSoft)),
          SizedBox(height: 5.px),
          TextField(
            controller: controller,
            keyboardType: isNumber ? TextInputType.number : TextInputType.text,
            decoration: const InputDecoration(contentPadding: EdgeInsets.symmetric(horizontal: 12, vertical: 8)),
          ),
        ],
      ),
    );
  }
}
